version: 2.1
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-browsers
    steps:
      - checkout
      - run:
          name: Clean
          command: mvn clean
      - run:
          name: Test
          command: mvn test
      - run:
          name: Generate Allure report
          command: mvn allure:report

      - store_test_results:
          path: target/surefire-reports/junitreports
      - store_artifacts:
          path: target/cucumber-html-reports/
      - store_artifacts:
          path: target/site/allure-maven-plugin/

workflows:
  commit:
    jobs:
      - test